import {
  Injectable,
  InternalServerErrorException,
  ServiceUnavailableException,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

type OllamaTagsResponse = {
  models?: Array<{
    name?: string;
  }>;
};

type OllamaGenerateResponse = {
  response?: string;
};

@Injectable()
export class AiService {
  private readonly baseUrl: string;
  private readonly primaryModel: string;
  private readonly fallbackModel: string;
  private readonly timeoutMs: number;
  private readonly maxRetries: number;

  constructor(private readonly configService: ConfigService) {
    this.baseUrl =
      this.configService.get<string>('OLLAMA_BASE_URL') ||
      'http://127.0.0.1:11434';
    this.primaryModel =
      this.configService.get<string>('OLLAMA_PRIMARY_MODEL') ||
      'qwen3.5:latest';
    this.fallbackModel =
      this.configService.get<string>('OLLAMA_FALLBACK_MODEL') ||
      'qwen2.5:3b';
    this.timeoutMs = Number(
      this.configService.get<string>('OLLAMA_TIMEOUT_MS') || 45000
    );
    this.maxRetries = Number(
      this.configService.get<string>('OLLAMA_MAX_RETRIES') || 1
    );
  }

  async getModels() {
    const tags = await this.fetchWithTimeout<OllamaTagsResponse>(
      `${this.baseUrl}/api/tags`
    );

    const models = (tags.models || [])
      .map(model => model.name)
      .filter((name): name is string => Boolean(name));

    return {
      baseUrl: this.baseUrl,
      configuredPrimary: this.primaryModel,
      configuredFallback: this.fallbackModel,
      availableModels: models,
    };
  }

  async getHealth() {
    try {
      const modelInfo = await this.getModels();
      const availableSet = new Set(modelInfo.availableModels);

      return {
        provider: 'ollama',
        baseUrl: modelInfo.baseUrl,
        status: 'ok',
        primaryModel: this.primaryModel,
        fallbackModel: this.fallbackModel,
        primaryAvailable: availableSet.has(this.primaryModel),
        fallbackAvailable: availableSet.has(this.fallbackModel),
        availableCount: modelInfo.availableModels.length,
      };
    } catch (error) {
      return {
        provider: 'ollama',
        baseUrl: this.baseUrl,
        status: 'down',
        primaryModel: this.primaryModel,
        fallbackModel: this.fallbackModel,
        error:
          error instanceof Error
            ? error.message
            : 'Ollama health check failed',
      };
    }
  }

  async generate(input: {
    prompt: string;
    system?: string;
    temperature?: number;
  }) {
    const modelsToTry =
      this.primaryModel === this.fallbackModel
        ? [this.primaryModel]
        : [this.primaryModel, this.fallbackModel];

    let lastError: unknown;

    for (const model of modelsToTry) {
      for (let attempt = 0; attempt <= this.maxRetries; attempt += 1) {
        try {
          const generated = await this.generateWithModel(model, input);
          return {
            model,
            response: generated,
            fallbackUsed: model !== this.primaryModel,
          };
        } catch (error) {
          lastError = error;
        }
      }
    }

    throw new ServiceUnavailableException(
      `AI generation failed for models [${modelsToTry.join(', ')}]: ${
        lastError instanceof Error ? lastError.message : 'unknown error'
      }`
    );
  }

  private async generateWithModel(
    model: string,
    input: { prompt: string; system?: string; temperature?: number }
  ) {
    const payload = {
      model,
      prompt: input.prompt,
      system: input.system,
      stream: false,
      options:
        input.temperature !== undefined
          ? { temperature: input.temperature }
          : undefined,
    };

    const result = await this.fetchWithTimeout<OllamaGenerateResponse>(
      `${this.baseUrl}/api/generate`,
      {
        method: 'POST',
        body: JSON.stringify(payload),
        headers: {
          'Content-Type': 'application/json',
        },
      }
    );

    if (!result.response) {
      throw new InternalServerErrorException(
        `No response generated by model ${model}`
      );
    }

    return result.response;
  }

  private async fetchWithTimeout<T>(url: string, init?: RequestInit): Promise<T> {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), this.timeoutMs);

    try {
      const response = await fetch(url, {
        ...init,
        signal: controller.signal,
      });

      if (!response.ok) {
        const details = await response.text();
        throw new ServiceUnavailableException(
          `Ollama request failed (${response.status}): ${details}`
        );
      }

      return (await response.json()) as T;
    } finally {
      clearTimeout(timeout);
    }
  }
}
